<a href="https://colab.research.google.com/github/piasmaciek/Machine-learning-bootcamp/blob/main/supervised/02_regression/02_spadek_wzdluz_gradientu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)

In [3]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000,3250,3500,3750,4000,4250])
m = len(X1)

print(f'Lata pracy:{X1}')
print(f'Wynagrodzenie:{Y}')
print(f'Liczba próbek:{m}')

Lata pracy:[1 2 3 4 5 6]
Wynagrodzenie:[3000 3250 3500 3750 4000 4250]
Liczba próbek:6


In [4]:
X1 = X1.reshape(m,1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [5]:
bias = np.ones((m,1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [6]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


In [7]:
eta = 0.01
weights = np.random.randn(2,1)
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[ 0.49671415]
 [-0.1382643 ]]


In [12]:
intercept = []
coef = []

for i in range(3000):
    gradient = ( 2 / m ) * X.T.dot(X.dot(weights) - Y)
    weights = weights - eta * gradient
    intercept.append(weights[0][0])
    coef.append(weights[1][0])

    print(weights)






Strumieniowane dane wyjściowe obcięte do 5000 ostatnich wierszy.
[[2.99528281e+03 3.24488964e+03 3.49449647e+03 3.74410331e+03
  3.99371014e+03 4.24331697e+03]
 [1.10183828e+00 1.19367433e+00 1.28551038e+00 1.37734643e+00
  1.46918249e+00 1.56101854e+00]]
[[2.99530003e+03 3.24490829e+03 3.49451656e+03 3.74412483e+03
  3.99373309e+03 4.24334136e+03]
 [1.09781719e+00 1.18931809e+00 1.28081899e+00 1.37231989e+00
  1.46382079e+00 1.55532170e+00]]
[[2.99531718e+03 3.24492688e+03 3.49453657e+03 3.74414627e+03
  3.99375596e+03 4.24336566e+03]
 [1.09381077e+00 1.18497775e+00 1.27614472e+00 1.36731170e+00
  1.45847867e+00 1.54964564e+00]]
[[2.99533427e+03 3.24494539e+03 3.49455651e+03 3.74416763e+03
  3.99377875e+03 4.24338987e+03]
 [1.08981898e+00 1.18065325e+00 1.27148751e+00 1.36232178e+00
  1.45315604e+00 1.54399031e+00]]
[[2.99535130e+03 3.24496384e+03 3.49457638e+03 3.74418891e+03
  3.99380145e+03 4.24341399e+03]
 [1.08584175e+00 1.17634452e+00 1.26684730e+00 1.35735007e+00
  1.44785284e+

In [13]:
intercept = []
coef = []

for i in range(3000):
    gradient = (2 / m) * X.T.dot(X.dot(weights) - Y)
    weights = weights - eta * gradient
    intercept.append(weights[0][0])
    coef.append(weights[1][0])

print(weights)

[[3.00000000e+03 3.25000000e+03 3.50000000e+03 3.75000000e+03
  4.00000000e+03 4.25000000e+03]
 [1.97436338e-07 2.13892091e-07 2.30348689e-07 2.46805213e-07
  2.63260678e-07 2.79715812e-07]]


In [16]:
df = pd.DataFrame(data={'intercept': intercept, 'coef': coef})
df.head()

intercept      coef
0  2999.951147  0.011411
1  2999.951325  0.011370
2  2999.951502  0.011328
3  2999.951679  0.011287
4  2999.951856  0.011246

In [18]:
px.line(df, y='intercept', width = 800, title='Dopasowanie: intercept')

In [19]:
px.line(df, y='coef', width = 800, title='Dopasowanie: intercept')